name: manage-azure-policy-f2b27487
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Allowed_virtual_machine_size_SKUs_cccc23c7-8427-4f53-ad12-b6a63eb452b3/**'
#      - 'policies/Disk_encryption_should_be_applied_on_virtual_machines_0961003e-5a0a-4549-abde-af6a37f2724d/**'
#      - 'policies/Add_system-assigned_managed_identity_to_enable_Guest_Configuration_assignments_on_virtual_machines_with_no_identities_3cf2ab00-13f1-4d0c-8971-2ac904541a7e/**'
#      - 'policies/The_Log_Analytics_agent_should_be_installed_on_virtual_machines_a70ca396-0a34-413a-88e1-b956c1e683be/**'
#      - .github/workflows/manage-azure-policy-f2b27487.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_f2b27487}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Allowed_virtual_machine_size_SKUs_cccc23c7-8427-4f53-ad12-b6a63eb452b3/**
          policies/Disk_encryption_should_be_applied_on_virtual_machines_0961003e-5a0a-4549-abde-af6a37f2724d/**
          policies/Add_system-assigned_managed_identity_to_enable_Guest_Configuration_assignments_on_virtual_machines_with_no_identities_3cf2ab00-13f1-4d0c-8971-2ac904541a7e/**
          policies/The_Log_Analytics_agent_should_be_installed_on_virtual_machines_a70ca396-0a34-413a-88e1-b956c1e683be/**
